### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/Mozilla-Italia-l10n-guide#57]
Few examples:
* `viceversa` and not `vice versa`

Also social pages:
* https://www.facebook.com/ModiGrammaticali/?fref=ts (I think that we can get graphics or other examples)

Why a glossary and not in the first chapter?
Because can be another resources to use like a dictionary when there are doubts instead of a chapter with rules. I think that can be very helpful because the chapters are for learning but a glossary is like a resource to use when you have a doubt.

**Comment by kitsunenosaraT** [comment]
Thank you for the example!
One of the next steps in version 2.0 of the guide will be to insert a lot of images (mainly screenshots of the UI) to make things easier to understand.

Regarding the usefulness of a glossary:
- we didn't include a proper glossary in the first chapter because it would become way too long.
Also, translation rules stay more or less the same, while glossaries need constant updating. So it makes more sense to have the glossary as an [external resource](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/resources/glossari/glossario-facebook.txt) to be updated independently instead of upgrading the guide each time we have to add a term.

- in addition, while a keeping a glossary ofrecurrent terms may come in handy sometimes, we encourage our translators to make use of the "glossary" functionality of official Translation Memories such as [Transvision](https://transvision.mozfr.org/) and Pontoon because it get automatically the latest terminology without us having to manually updating it.

**Comment by Mte90** [comment]
Ok I didn't know about the glossary in txt format.
It will be useful if it is like in csv format so it is possible to use with software like Calc or Excel. I was thinking that in case will be possible to do a web interface to search that terms and show :-)

**Comment by kitsunenosaraT** [comment]
About that, our txt glossary is tab delimited data.
That means you can import it neatly in spreadsheets with the option "Import as tab delimited text file".
It's a format I use in my translation work to import/export my terminology back and forth between translation tools. Basically I store the terms as txt, but use spreadsheets to edit it because it has more functions.

The structure is:
*English term* [tab] *Italian translation* [tab] *comments* [return]

If I recall correctly, @gialloporpora once made a web search interface for this?

**Comment by eliogi** [comment]
Ciao a tutti, non so se questo è il posto giusto per chiedere, ma cosa sono le stringhe Fuzzy?

![schermata 2017-10-12 alle 11 53 31](https://user-images.githubusercontent.com/11160857/31490614-e504366c-af44-11e7-9061-9c15ccd637d8.png)

**Comment by kitsunenosaraT** [comment]
@eliogi trovi la definizione nel capitolo 3 della guida, per l'esattezza in [questo paragrafo](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md#interfaccia-e-navigazione) 😉

**Comment by eliogi** [comment]
Grazie Sara, me l'ero dimenticato... ora ricordo il paragafo. Sorry non lo faccio più, ti prometto che leggo una volta al mese tutti i documenti fino a impararli a memoria (questa è la punzione 😄 )

A parte gli scherzi, ok ora è tutto chiaro.

**Comment by kitsunenosaraT** [comment]
Penso che qui possiamo chiudere, visto che gli argomenti trattati sono esauriti.
