### ISSUE TITLE
Migrate on MozillaItalia organization

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/Mozilla-Italia-l10n-guide#58]
As a remainder to migrate the repo in the organization in that way is very official :-D

**Comment by kitsunenosaraT** [comment]
👍

**Comment by Mte90** [comment]
We have some deadline by the way? like when all the tickets are closed or when is stable?

**Comment by kitsunenosaraT** [comment]
Actually no, unless you want to have it migrated in time for the Libre Office conference in October, in order to make it more "official".
The only thing that is keeping me from migrating is that I intend to upload images in next version in the guide. Since I don't know if I can manage it without major disasters, I figured out that it would be better to do it while in my own repository, to limit inconveniences for other users in case something goes bad... 😅

**Comment by Mte90** [comment]
Well no worry in case of destruction because in the organization is the same like in your personal.
In any case we can wait few weeks for the libreconf :-)

**Comment by Mte90** [comment]
Done!
